In [1]:
lista=[]
suma=0.0
for i in range(0,101):
    suma=suma+i
    lista.append(suma)
print(lista)

[0.0, 1.0, 3.0, 6.0, 10.0, 15.0, 21.0, 28.0, 36.0, 45.0, 55.0, 66.0, 78.0, 91.0, 105.0, 120.0, 136.0, 153.0, 171.0, 190.0, 210.0, 231.0, 253.0, 276.0, 300.0, 325.0, 351.0, 378.0, 406.0, 435.0, 465.0, 496.0, 528.0, 561.0, 595.0, 630.0, 666.0, 703.0, 741.0, 780.0, 820.0, 861.0, 903.0, 946.0, 990.0, 1035.0, 1081.0, 1128.0, 1176.0, 1225.0, 1275.0, 1326.0, 1378.0, 1431.0, 1485.0, 1540.0, 1596.0, 1653.0, 1711.0, 1770.0, 1830.0, 1891.0, 1953.0, 2016.0, 2080.0, 2145.0, 2211.0, 2278.0, 2346.0, 2415.0, 2485.0, 2556.0, 2628.0, 2701.0, 2775.0, 2850.0, 2926.0, 3003.0, 3081.0, 3160.0, 3240.0, 3321.0, 3403.0, 3486.0, 3570.0, 3655.0, 3741.0, 3828.0, 3916.0, 4005.0, 4095.0, 4186.0, 4278.0, 4371.0, 4465.0, 4560.0, 4656.0, 4753.0, 4851.0, 4950.0, 5050.0]


In [6]:
N=int(input("a que número le quieres sacar el factorial?"))
factorial=1 #neutro multiplicativo
for i in range(1,N+1):
    factorial=factorial*i
print(factorial)

a que número le quieres sacar el factorial? 40


815915283247897734345611269596115894272000000000


In [1]:
a=2
b=1.99
c="2"
print(a==b)
print((a>b) and (a!=c))
print((a>b) or (a!=c))
print((a==b) and (a!=c))

False
True
True
False


In [1]:
from cmath import * 
z1 = 3+4*1j
z2 = 1+2*1j 

In [3]:
print(z1*z2 + z2**2)

(-8+14j)


In [4]:
z1**2

(-7+24j)

In [6]:
x=int(input("da un entero positivo"))
if x%2==0:
    print("par")
else:
    print("impar")

da un entero positivo 91


impar


In [7]:
x=int(input("da un entero positivo"))
if x%2==0:
    print("x es un par")
elif x%3==0:
    print("x es divisible entre 3")
elif x%5==0:
    print("x es divisible por 5")
else:
    print("suerte pa la próxima")

da un entero positivo 56


x es un par


In [19]:
x=int(input("da una temperatura en Celsius"))
print("la temperatura en kelvin es:", x+273)
print("la temperatura en farenheit es:", x*1.8+32)


da una temperatura en Celsius 0


la temperatura en kelvin es: 273
la temperatura en farenheit es: 32.0


In [22]:
print("contador de 0 hasta 10")
contador =0
while contador <=10:
    print(contador)
    contador+=1

contador de 0 hasta 10
0
1
2
3
4
5
6
7
8
9
10


In [26]:
from random import choice
l_random=[1,2,3,4,5,6,7,8,9,10]
print(choice(l_random))

6


In [33]:
#Gato de Shrodinger
from random import choice
gato=["vivo", "muerto"]
n=int(input("Cuántas veces harás el experimento?"))
i,i_vivo=0,0
while i<=n:
    x=choice(gato)
    i+=1 #contamos cuantas veces se hace el experimento
    if x=="vivo":
        i_vivo+=1 #contamos cuantas veces resulto vivo
print("el gato apareció vivo %d de %d veces"%(i_vivo,n))

Cuántas veces harás el experimento? 60


el gato apareció vivo 31 de 60 veces


In [34]:
tuple1=("Arciniega", "Armando", (23,10))

In [36]:
apellido, nombre, cumpleaños = tuple1
print(nombre,apellido,"cumleaños es", cumpleaños[0])

Armando Arciniega cumleaños es 23


In [37]:
lista=[1,2,3]

In [41]:
def factorial(n):
    prod=1
    for i in range(1,n+1):
        prod=prod*i
    return prod 

In [45]:
def binomial(n,k):
    binom=factorial(n)/(factorial(k)*factorial(n-k))
    return binom 
print("imprimir renglon triangulo de pastcal")
print(binomial(2,0), binomial(2,1), binomial(2,2))

imprimir renglon triangulo de pastcal
1.0 2.0 1.0


In [47]:
print("haremos una función renglon que guarde el renglon bla  bla")
def renglon(n):
    lista=[]
    for k in range(0, n+1):
        lista.append(binomial(n,k))
    return lista
for i in range(11):
    print(renglon(i))

haremos una función renglon que guarde el renglon bla  bla
[1.0]
[1.0, 1.0]
[1.0, 2.0, 1.0]
[1.0, 3.0, 3.0, 1.0]
[1.0, 4.0, 6.0, 4.0, 1.0]
[1.0, 5.0, 10.0, 10.0, 5.0, 1.0]
[1.0, 6.0, 15.0, 20.0, 15.0, 6.0, 1.0]
[1.0, 7.0, 21.0, 35.0, 35.0, 21.0, 7.0, 1.0]
[1.0, 8.0, 28.0, 56.0, 70.0, 56.0, 28.0, 8.0, 1.0]
[1.0, 9.0, 36.0, 84.0, 126.0, 126.0, 84.0, 36.0, 9.0, 1.0]
[1.0, 10.0, 45.0, 120.0, 210.0, 252.0, 210.0, 120.0, 45.0, 10.0, 1.0]


# Listas

In [ ]:
n=int(input("Que dimension tiene tu arreglo?"))
A=[]
#hacemos un arreglo de nxn de ceros
print([0]*3)
for i in range(n):
    A.append([0]*n)
print(A)
#luego , pedimos elemento por elemento
for i in range(n):#pedimos renglones
    for j in range(n): #pedimos columnas
        A[i][j]=int(input("da el elemento (%d,%d)"%(i,j))) 
print(A)

In [3]:
def matriz(m,n):
    A=[]
    for i in range(n):
        A.append([0] * n)
        for i in range(m):
            for j in range(n): 
                A[i][j]=float(input("da el elemento [%d,%d]=\t%()")) 
    return(A)

    
    

In [ ]:
matriz(2,4)

In [6]:
from numpy import * 
arreglo2=array([[1,2,3],[4,5,6]],int)
print(arreglo2)
print("primer elemento del arreglo", arreglo2[0,0])

[[1 2 3]
 [4 5 6]]
primer elemento del arreglo 1


#### la funcion array crea un arreglo de listas especificando que tipo de variables se tienen

In [23]:
import numpy as np
def transpuesta(A):
    n=len(A)
    m=len(A[0])
    B=np.zeros((m,n))  #Se crea el espacio de la matriz, esta ya tiene las dimensiones de la Matriz transpuesta
    for i in range(n):
        for j in range(m):
            B[j][i]=A[i][j] #Aquí se llena la matrz
            #B[i,j] = A[j,i]
    return(B)
    


In [21]:
H=[[1,2,3],[4,5,6],[7,8,9]]


In [22]:
transpuesta(H)

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

#### Conjugado de un número complejo

$z = 1 + 1j$

In [25]:
from cmath import *
def conjugado(A):
    n=len(A)
    m=len(A[0])
    B=zeros([m,n],complex) #creamos el espacio en la memoria
    for i in range(m):
            B[i,j]=A[i,j]*(-1j)  #-1j python lo lee como un número complejo, la unidad compleja
    return(B)

A=array([[1+1j,1+1j] , [1+1j,1+1j]] )

### Tiempo de cómputo


In [57]:
from numpy import *
import time 
t0=time.time()
A=ones([10,10])
B=ones([10,10])
C=ones([10,10])
for i in range(10):
    for j in range(10):
        for k in range(10):
            C[i,j]+=A[i,k]*B[k,j]
print(C)
print(time.time()-t0)

[[11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]
 [11. 11. 11. 11. 11. 11. 11. 11. 11. 11.]]
0.003448486328125


In [56]:
import multiprocessing as mp
print("Number of processors: ", mp.cpu_count())

Number of processors:  16


#### Primer algoritmo, ecuaciones de 1er grado

$\vec{A}\cdot \vec{x} = \vec{v}$

In [54]:
A = array[[4,-1,-1,-1]
          [-1, 0, 3,0]
          [-1, 3,0,-1]
          [-1,-1,0,-1],float]
v=array[[5,5,0,0],float]
N = len(v)
#escalonamos
for i in range(N): #recorro los renglones
    div = A[m,m] #hago "unos" en la diagonal
    A[m,:] /= div
    v[m] /= div
    
    
    for i in range(m+1,N):
        mult = A[i,m]  #multiplico 
        A[i,:] -= mult*A[m,:]
        v[i] -= mult*v[m]
        
x=empty(N,float)
for m in range(N-1,-1,-1): # de abajo hacia rriba
    x[m] = v[m]
    for i in range(m+1,N): #
        x[m] -= A[m,i]*x[i]